/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MathRouteImport } from './routes/math'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CashierRouteImport } from './routes/cashier'
import { Route as ArabicRouteImport } from './routes/arabic'
import { Route as IndexRouteImport } from './routes/index'

const MathRoute = MathRouteImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierRoute = CashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const ArabicRoute = ArabicRouteImport.update({
  id: '/arabic',
  path: '/arabic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arabic': typeof ArabicRoute
  '/cashier': typeof CashierRoute
  '/history': typeof HistoryRoute
  '/math': typeof MathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arabic': typeof ArabicRoute
  '/cashier': typeof CashierRoute
  '/history': typeof HistoryRoute
  '/math': typeof MathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arabic': typeof ArabicRoute
  '/cashier': typeof CashierRoute
  '/history': typeof HistoryRoute
  '/math': typeof MathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arabic' | '/cashier' | '/history' | '/math'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arabic' | '/cashier' | '/history' | '/math'
  id: '__root__' | '/' | '/arabic' | '/cashier' | '/history' | '/math'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArabicRoute: typeof ArabicRoute
  CashierRoute: typeof CashierRoute
  HistoryRoute: typeof HistoryRoute
  MathRoute: typeof MathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/math': {
      id: '/math'
      path: '/math'
      fullPath: '/math'
      preLoaderRoute: typeof MathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier': {
      id: '/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof CashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arabic': {
      id: '/arabic'
      path: '/arabic'
      fullPath: '/arabic'
      preLoaderRoute: typeof ArabicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArabicRoute: ArabicRoute,
  CashierRoute: CashierRoute,
  HistoryRoute: HistoryRoute,
  MathRoute: MathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
