/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TraceRouteImport } from './routes/trace'
import { Route as RaceRouteImport } from './routes/race'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as MathRouteImport } from './routes/math'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HiddenRouteImport } from './routes/hidden'
import { Route as CashierRouteImport } from './routes/cashier'
import { Route as ArabicRouteImport } from './routes/arabic'
import { Route as IndexRouteImport } from './routes/index'

const TraceRoute = TraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceRoute = RaceRouteImport.update({
  id: '/race',
  path: '/race',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const MathRoute = MathRouteImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HiddenRoute = HiddenRouteImport.update({
  id: '/hidden',
  path: '/hidden',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierRoute = CashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const ArabicRoute = ArabicRouteImport.update({
  id: '/arabic',
  path: '/arabic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arabic': typeof ArabicRoute
  '/cashier': typeof CashierRoute
  '/hidden': typeof HiddenRoute
  '/history': typeof HistoryRoute
  '/math': typeof MathRoute
  '/parent': typeof ParentRoute
  '/race': typeof RaceRoute
  '/trace': typeof TraceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arabic': typeof ArabicRoute
  '/cashier': typeof CashierRoute
  '/hidden': typeof HiddenRoute
  '/history': typeof HistoryRoute
  '/math': typeof MathRoute
  '/parent': typeof ParentRoute
  '/race': typeof RaceRoute
  '/trace': typeof TraceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arabic': typeof ArabicRoute
  '/cashier': typeof CashierRoute
  '/hidden': typeof HiddenRoute
  '/history': typeof HistoryRoute
  '/math': typeof MathRoute
  '/parent': typeof ParentRoute
  '/race': typeof RaceRoute
  '/trace': typeof TraceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arabic'
    | '/cashier'
    | '/hidden'
    | '/history'
    | '/math'
    | '/parent'
    | '/race'
    | '/trace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arabic'
    | '/cashier'
    | '/hidden'
    | '/history'
    | '/math'
    | '/parent'
    | '/race'
    | '/trace'
  id:
    | '__root__'
    | '/'
    | '/arabic'
    | '/cashier'
    | '/hidden'
    | '/history'
    | '/math'
    | '/parent'
    | '/race'
    | '/trace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArabicRoute: typeof ArabicRoute
  CashierRoute: typeof CashierRoute
  HiddenRoute: typeof HiddenRoute
  HistoryRoute: typeof HistoryRoute
  MathRoute: typeof MathRoute
  ParentRoute: typeof ParentRoute
  RaceRoute: typeof RaceRoute
  TraceRoute: typeof TraceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trace': {
      id: '/trace'
      path: '/trace'
      fullPath: '/trace'
      preLoaderRoute: typeof TraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race': {
      id: '/race'
      path: '/race'
      fullPath: '/race'
      preLoaderRoute: typeof RaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math': {
      id: '/math'
      path: '/math'
      fullPath: '/math'
      preLoaderRoute: typeof MathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hidden': {
      id: '/hidden'
      path: '/hidden'
      fullPath: '/hidden'
      preLoaderRoute: typeof HiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier': {
      id: '/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof CashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arabic': {
      id: '/arabic'
      path: '/arabic'
      fullPath: '/arabic'
      preLoaderRoute: typeof ArabicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArabicRoute: ArabicRoute,
  CashierRoute: CashierRoute,
  HiddenRoute: HiddenRoute,
  HistoryRoute: HistoryRoute,
  MathRoute: MathRoute,
  ParentRoute: ParentRoute,
  RaceRoute: RaceRoute,
  TraceRoute: TraceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
